---
title: "Capstone project - outline"

# to produce blinded version set to 1
blinded: 0

authors: 
- name: Nicole Frontero
  affiliation: Department of Mathematics and Statistics, Amherst College
  

keywords:
- I'll need to add keywords

abstract: |
  Once I've written the report I'll add an abstract

bibliography: bibliography.bib
output:
  rticles::asa_article:
  keep_tex: yes
---

```{r setup, include = FALSE}
library(tidyverse)
library(mosaic)
library(mdsr)
library(knitr)
library(kableExtra)
library(ggplot2)
library(sf)
```

*Note that I will include a table of contents*

# Introduction
Here I will discuss why I chose this topic and will preview what the report contains.

## Motivation
Motivations include: 

* I have long had an interest in maps (since childhood)
* I wish I had access to a Shiny app like this when I was at Amherst
* I have no exposure to working with GIS data so this will be a challenge

## Overview of the paper
I will go through the structure of the paper (subject to change).

# Expository review

## Basics of working with geospatial data
Here I will cover the very basics of geospatial data. 

### Why is it worthwhile to work with geospatial data? 
MDSR section 17.1 provides a good example of why geospatial data can be helpful.  I plan to come up with my own example (similar to the cholera deaths example) and/or list some examples of how geospatial data is ubiquitous in modern society: for example, think Google Earth, weather radar maps, GPS systems, etc.

### Geospatial data files

I will first emphasize that there are *a lot* of different GIS data file types. I might give some as examples.  Then, I will focus primariy on the file types that I will be utilizing (shp, shx, dbf).  I will discuss the functions/packages I will heavily relying upon to read the files/use them in R. 

### Projections

I will give a general overview of the concept of projections.  I will also include some images that show drastically different portrayals of Earth in 2D depending upon the projections used. 

## Geospatial computations

I will try to emphasize in this section that geospatial computations sound scary but aren't!

### Computing distance

I'll go into how distance is computed.  

### Elevation charts

I'll go into how elevation is computed.

# Shiny app

The Shiny app portion of the report will include, for each aspect of the app:

* A brief introduction as to why I am including that aspect in the app
* Coding that I did
* A screen shot of that aspect of the app 
* A brief ending few sentences to wrap up the subsection

## Data wrangling

At present I plan to put the data wrangling in the Shiny app section, but I might make this its own section. 

## Elevation charts

## Length of trails

## Trail categorization scheme

## Points of interest layer

## Waypoints layer

## Trail type layer

## Engaging with the Shiny app

Here I'll put instructions for how to use the Shiny app (if necessary).  I will also highlight particularly clever features of the app (if applicable).

# Conclusion

I'll wrap up the report here, and will cover:

* Recall: motivation
* Review of what I did
* Why this is novel
* Why I'm proud of it

\newpage
